//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenEgozi.Demos.MR.Web.SiteMap {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootHelloControllerActionNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference World() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "World", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "World", new System.Type[0]), new Castle.Tools.CodeGenerator.Model.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootLendablesControllerActionNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference Index() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Index", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Index", new System.Type[0]), new Castle.Tools.CodeGenerator.Model.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference Index(string q) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Index", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Index", new System.Type[] {
                            typeof(string)}), new Castle.Tools.CodeGenerator.Model.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.Model.ActionArgument(0, "q", typeof(string), q)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference NewBook() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "NewBook", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "NewBook", new System.Type[0]), new Castle.Tools.CodeGenerator.Model.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference NewDvd() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "NewDvd", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "NewDvd", new System.Type[0]), new Castle.Tools.CodeGenerator.Model.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference Save(KenEgozi.Demos.MR.Web.Domain.Entities.Book book) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Save", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Save", new System.Type[] {
                            typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Book)}), new Castle.Tools.CodeGenerator.Model.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.Model.ActionArgument(0, "book", typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Book), book)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference Save(KenEgozi.Demos.MR.Web.Domain.Entities.Dvd dvd) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Save", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Save", new System.Type[] {
                            typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Dvd)}), new Castle.Tools.CodeGenerator.Model.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.Model.ActionArgument(0, "dvd", typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Dvd), dvd)});
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootRescuesControllerActionNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference ShowError() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "", "Rescues", "ShowError", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "ShowError", new System.Type[0]), new Castle.Tools.CodeGenerator.Model.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerActionReference GeneralError() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "", "Rescues", "GeneralError", new Castle.Tools.CodeGenerator.Model.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "GeneralError", new System.Type[0]), new Castle.Tools.CodeGenerator.Model.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootHelloControllerRouteNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootLendablesControllerRouteNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootRescuesControllerRouteNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootHelloControllerViewNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference time {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "time");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference view {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "view");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootLendablesControllerViewNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference Book {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Book");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference DVD {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "DVD");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference Index {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Index");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference List {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "List");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference NewBook {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "NewBook");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference NewDvd {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "NewDvd");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        public RootRescuesControllerViewNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.Model.IControllerViewReference GeneralError {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "", "Rescues", "GeneralError");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootAreaNode {
        
        protected Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices _services;
        
        private RootHelloControllerNode _hello;
        
        private RootLendablesControllerNode _lendables;
        
        private RootRescuesControllerNode _rescues;
        
        public RootAreaNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) {
            this._services = services;
            this._hello = new RootHelloControllerNode(this._services);
            this._lendables = new RootLendablesControllerNode(this._services);
            this._rescues = new RootRescuesControllerNode(this._services);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHelloControllerNode Hello {
            get {
                return this._hello;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLendablesControllerNode Lendables {
            get {
                return this._lendables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootRescuesControllerNode Rescues {
            get {
                return this._rescues;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerNode : RootHelloControllerActionNode {
        
        public RootHelloControllerNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHelloControllerViewNode Views {
            get {
                return new RootHelloControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHelloControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerNode : RootLendablesControllerActionNode {
        
        public RootLendablesControllerNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLendablesControllerViewNode Views {
            get {
                return new RootLendablesControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLendablesControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerNode : RootRescuesControllerActionNode {
        
        public RootRescuesControllerNode(Castle.Tools.CodeGenerator.Services.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootRescuesControllerViewNode Views {
            get {
                return new RootRescuesControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootRescuesControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
}
namespace KenEgozi.Demos.MR.Web.Controllers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class HelloController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerNode MyActions {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerViewNode MyViews {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerRouteNode MyRoutes {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class LendablesController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerNode MyActions {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerViewNode MyViews {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerRouteNode MyRoutes {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RescuesController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerNode MyActions {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerViewNode MyViews {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerRouteNode MyRoutes {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
}
