//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenEgozi.Demos.MR.Web.SiteMap {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPetsControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPetsControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Cats(int page, string orderBy, string sortOrder) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "Cats", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "Cats", new System.Type[] {
                            typeof(int),
                            typeof(string),
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "page", typeof(int), page),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(1, "orderBy", typeof(string), orderBy),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(2, "sortOrder", typeof(string), sortOrder)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference Cats() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "Cats", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "Cats", new System.Type[] {
                            typeof(int),
                            typeof(string),
                            typeof(string)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference CatsGrid() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "CatsGrid", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "CatsGrid", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference CatsList(int page, string sidx, string sord, int rows) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "CatsList", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "CatsList", new System.Type[] {
                            typeof(int),
                            typeof(string),
                            typeof(string),
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "page", typeof(int), page),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(1, "sidx", typeof(string), sidx),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(2, "sord", typeof(string), sord),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(3, "rows", typeof(int), rows)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference CatsList() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "CatsList", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "CatsList", new System.Type[] {
                            typeof(int),
                            typeof(string),
                            typeof(string),
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Cat(int id) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "Cat", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "Cat", new System.Type[] {
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "id", typeof(int), id)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Cat(KenEgozi.Demos.MR.Web.Domain.Entities.Cat cat) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "Cat", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "Cat", new System.Type[] {
                            typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Cat)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "cat", typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Cat), cat)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Cat(int id, string name, KenEgozi.Demos.MR.Web.Domain.Entities.Gender gender, int age) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "Cat", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "Cat", new System.Type[] {
                            typeof(int),
                            typeof(string),
                            typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Gender),
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "id", typeof(int), id),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(1, "name", typeof(string), name),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(2, "gender", typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Gender), gender),
                        new Castle.Tools.CodeGenerator.External.ActionArgument(3, "age", typeof(int), age)});
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootHelloControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference World() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "World", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "World", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference View() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "View", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "View", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Time() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "Time", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "Time", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference CachedTime() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "CachedTime", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "CachedTime", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootLendablesControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Index() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Index", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Index", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Index(string[] q) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Index", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Index", new System.Type[] {
                            typeof(string[])}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "q", typeof(string[]), q)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference NewBook() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "NewBook", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "NewBook", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference NewDvd() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "NewDvd", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "NewDvd", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Edit(int id) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Edit", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Edit", new System.Type[] {
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "id", typeof(int), id)});
        }
        
        // Empty argument Action... Not sure if we want to pass MethodInformation to these...
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IArgumentlessControllerActionReference Edit() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Edit", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Edit", new System.Type[] {
                            typeof(int)}), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Save(KenEgozi.Demos.MR.Web.Domain.Entities.Book book) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Save", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Save", new System.Type[] {
                            typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Book)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "book", typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Book), book)});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference Save(KenEgozi.Demos.MR.Web.Domain.Entities.Dvd dvd) {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Save", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "Save", new System.Type[] {
                            typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Dvd)}), new Castle.Tools.CodeGenerator.External.ActionArgument[] {
                        new Castle.Tools.CodeGenerator.External.ActionArgument(0, "dvd", typeof(KenEgozi.Demos.MR.Web.Domain.Entities.Dvd), dvd)});
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerActionNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootRescuesControllerActionNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference ShowError() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "", "Rescues", "ShowError", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "ShowError", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerActionReference GeneralError() {
            return this._services.ControllerReferenceFactory.CreateActionReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "", "Rescues", "GeneralError", new Castle.Tools.CodeGenerator.External.MethodSignature(typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "GeneralError", new System.Type[0]), new Castle.Tools.CodeGenerator.External.ActionArgument[0]);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPetsControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPetsControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootHelloControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootLendablesControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerRouteNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootRescuesControllerRouteNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPetsControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootPetsControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Cat {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "Cat");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Cats {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "Cats");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference CatsGrid {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "CatsGrid");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference EditCat {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.PetsController), "", "Pets", "EditCat");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootHelloControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference time {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "time");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference view {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.HelloController), "", "Hello", "view");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootLendablesControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Book {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Book");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference DVD {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "DVD");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference EditBook {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "EditBook");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference EditDvd {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "EditDvd");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference Index {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "Index");
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference List {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.LendablesController), "", "Lendables", "List");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerViewNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        public RootRescuesControllerViewNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual Castle.Tools.CodeGenerator.External.IControllerViewReference GeneralError {
            get {
                return this._services.ControllerReferenceFactory.CreateViewReference(this._services, typeof(KenEgozi.Demos.MR.Web.Controllers.RescuesController), "", "Rescues", "GeneralError");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootAreaNode {
        
        protected Castle.Tools.CodeGenerator.External.ICodeGeneratorServices _services;
        
        private RootPetsControllerNode _pets;
        
        private RootHelloControllerNode _hello;
        
        private RootLendablesControllerNode _lendables;
        
        private RootRescuesControllerNode _rescues;
        
        public RootAreaNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) {
            this._services = services;
            this._pets = new RootPetsControllerNode(this._services);
            this._hello = new RootHelloControllerNode(this._services);
            this._lendables = new RootLendablesControllerNode(this._services);
            this._rescues = new RootRescuesControllerNode(this._services);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPetsControllerNode Pets {
            get {
                return this._pets;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHelloControllerNode Hello {
            get {
                return this._hello;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLendablesControllerNode Lendables {
            get {
                return this._lendables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootRescuesControllerNode Rescues {
            get {
                return this._rescues;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootPetsControllerNode : RootPetsControllerActionNode {
        
        public RootPetsControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPetsControllerViewNode Views {
            get {
                return new RootPetsControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootPetsControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootHelloControllerNode : RootHelloControllerActionNode {
        
        public RootHelloControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHelloControllerViewNode Views {
            get {
                return new RootHelloControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootHelloControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootLendablesControllerNode : RootLendablesControllerActionNode {
        
        public RootLendablesControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLendablesControllerViewNode Views {
            get {
                return new RootLendablesControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootLendablesControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RootRescuesControllerNode : RootRescuesControllerActionNode {
        
        public RootRescuesControllerNode(Castle.Tools.CodeGenerator.External.ICodeGeneratorServices services) : 
                base(services) {
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootRescuesControllerViewNode Views {
            get {
                return new RootRescuesControllerViewNode(this._services);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual RootRescuesControllerActionNode Actions {
            get {
                return this;
            }
        }
    }
}
namespace KenEgozi.Demos.MR.Web.Controllers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class PetsController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootPetsControllerNode MyActions {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootPetsControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootPetsControllerViewNode MyViews {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootPetsControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootPetsControllerRouteNode MyRoutes {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootPetsControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class HelloController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerNode MyActions {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerViewNode MyViews {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerRouteNode MyRoutes {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootHelloControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class LendablesController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerNode MyActions {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerViewNode MyViews {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerRouteNode MyRoutes {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootLendablesControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Castle.Tools.CodeGenerator", "0.2")]
    public partial class RescuesController {
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerNode MyActions {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerViewNode MyViews {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerViewNode(this.CodeGeneratorServices);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public virtual KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerRouteNode MyRoutes {
            get {
                return new KenEgozi.Demos.MR.Web.SiteMap.RootRescuesControllerRouteNode(this.CodeGeneratorServices);
            }
        }
        
        protected override void PerformGeneratedInitialize() {
            base.PerformGeneratedInitialize();
            this.PropertyBag["MyViews"] = this.MyViews;
            this.PropertyBag["MyActions"] = this.MyActions;
            this.PropertyBag["MyRoutes"] = this.MyRoutes;
        }
    }
}
